---

- name: Config passmanager host 
  hosts: jenkins-pro
  become: true
  vars_files:
    - vars/repos.yml
  roles:
     - { 
         role: ansible-role-smd-bootstrap,
         smd_repos_repo_proxy: 'http://proxy2pdi.service.dsn.inet:6666',
         smd_bootstrap_role_repos_enabled: true,
         smd_bootstrap_role_chrony_enabled: true,
         smd_bootstrap_role_timezone_enabled: true,
         smd_bootstrap_role_rhn_enabled: false,
         smd_boostrap_role_update_so_enabled: false
       } 
     - { role: ansible-role-smd-docker,
         smd_docker_proxy: 'http://proxy2pdi.service.dsn.inet:6666',
         smd_docker_lvm_config: false,
         smd_docker_storage_device: /dev/vdc,
         smd_docker_bind_network: DOCKER_MGMT,
         smd_docker_bind_port: 2376
       }
       

